#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokemonMobileClient.Resource", IsApplication=true)]

namespace PokemonMobileClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abraicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aerodactylicon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int alakazamicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arbokicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arcanineicon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int articunoicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int beedrillicon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bellsprouticon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int blastoiseicon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bulbasauricon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int butterfreeicon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int caterpieicon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chanseyicon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int charizardicon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int charmandericon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int charmeleonicon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int clefableicon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int clefairyicon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cloystericon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cuboneicon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int dewgongicon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int digletticon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int dittoicon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int dodrioicon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int doduoicon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dragonairicon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dragoniteicon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dratiniicon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int drowzeeicon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dugtrioicon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int eeveeicon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ekansicon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int electabuzzicon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int electrodeicon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int exeggcuteicon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int exeggutoricon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int farfetchdicon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int fearowicon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int flareonicon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int gastlyicon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int gengaricon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int geodudeicon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int gloomicon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int golbaticon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int goldeenicon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int golduckicon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int golemicon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int gravelericon = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int grimericon = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int growlitheicon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int gyaradosicon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int hauntericon = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int hitmonchanicon = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int hitmonleeicon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int horseaicon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int hypnoicon = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ivysauricon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int jigglypufficon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int jolteonicon = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int jynxicon = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int kabutoicon = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int kabutopsicon = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int kadabraicon = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int kakunaicon = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int kangaskhanicon = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int kinglericon = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int koffingicon = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int krabbyicon = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int laprasicon = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int lickitungicon = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int machampicon = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int machokeicon = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int machopicon = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int magikarpicon = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int magmaricon = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int magnemiteicon = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int magnetonicon = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int mankeyicon = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int marowakicon = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int meowthicon = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int metapodicon = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int mewicon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int mewtwoicon = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int moltresicon = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int mrmimeicon = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int mukicon = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int nidokingicon = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int nidoqueenicon = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int nidoranicon = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int nidoranmicon = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int nidorinaicon = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int nidorinoicon = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ninetailsicon = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int oddishicon = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int omanyteicon = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int omastaricon = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int onixicon = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int parasecticon = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int parasicon = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int persianicon = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int pidgeoticon = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int pidgeottoicon = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int pidgeyicon = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int pikachuicon = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int pinsiricon = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int pokedex = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int pokedexMainActivity = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int poliwagicon = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int poliwhirlicon = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int poliwrathicon = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ponytaicon = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int porygonicon = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int primeapeicon = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int psyduckicon = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int raichuicon = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int rapidashicon = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int raticateicon = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int rattataicon = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int redbutton = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int rhydonicon = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int rhyhornicon = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int sandshrewicon = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int sandslashicon = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int scythericon = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int seadraicon = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int seakingicon = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int seelicon = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int shelldericon = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int slowbroicon = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int slowpokeicon = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int snorlaxicon = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int spearowicon = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int squirtleicon = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int starmieicon = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int staryuicon = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int tangelaicon = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int taurosicon = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int tentacoolicon = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int tentacruelicon = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int vaporeonicon = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int venomothicon = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int venonaticon = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int venusauricon = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int victreebelicon = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int vileplumeicon = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int voltorbicon = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int vulpixicon = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int wartortleicon = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int weedleicon = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int weepinbellicon = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int weezingicon = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int wigglytufficon = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int zapdosicon = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int zubaticon = 2130837658;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int contactEmailAddressTextField = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int contactMessageTextField = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int contactSendFeedback = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int mainAboutButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int mainAllPokemonButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int mainViewImage = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int pokemonIconImageView = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int pokemonListActivityListView = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int pokemonRowTextView = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int pokemonTypeRowView = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PokemonListActivityView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PokemonRowView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
