// <auto-generated />
namespace PokemonAppCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_nullableInt_pokemonMoves_levelGained : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_nullableInt_pokemonMoves_levelGained));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050425595_add_nullableInt_pokemonMoves_levelGained"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
